name: Build and deploy gender API

on:
  push:
    branches:
      - 'main'

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3

      - name: Auth GCP gcloud
        uses: 'google-github-actions/auth@v1'
        with:
            credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Build docker
        run: docker build -t flask-api .

      - name: Tag the image
        run: docker tag flask-api europe-docker.pkg.dev/ensai-2025/gender-chat-europe/flask-api

      - name: Authenticate to GCP registry
        run: gcloud auth configure-docker europe-docker.pkg.dev

      - name: Push to GCP registry
        run: docker push europe-docker.pkg.dev/ensai-2025/gender-chat-europe/flask-api